# This is purely a development setup. DO NOT RUN THIS IN PRODUCTION
version: '3.7'

services:
  # NOTE: You will need to up the max map count on your system
  #       sudo sysctl -w vm.max_map_count=262144
  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    networks:
      docker-elk:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./tmp/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.9.3
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - docker-elk
    depends_on:
      - elasticsearch

  redis:
    image: redis:5.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis:/data
    networks:
      - docker-elk

  postgres:
    image: postgres
    container_name: postgres
    environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    networks:
      - docker-elk

  api-db:
    image: postgres
    container_name: api-db
    environment:
        POSTGRES_DB: cocus
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql-api-db/data
    networks:
      - docker-elk

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    volumes:
      - ./keycloak/realm_common.json:/tmp/my_realm.json
    environment:
      KEYCLOAK_IMPORT: '/tmp/my_realm.json'
      JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.profile.feature.declarative_user_profile=enabled"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
    ports:
      - 8080:8080
    networks:
      - docker-elk

  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    ports:
      - "4566-4583:4566-4583"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - docker-elk

networks:
  docker-elk:
    driver: bridge